### ISSUE TITLE
shiftfs-module-loader erroring

### ISSUE THREAD

**Issue by mrsimonemms** [MrSimonEmms/gitpod-k3s-guide#5]
The `shiftfs-module-loader` init container is erroring and not sure of the root cause. It's probable that it's either a missing dependency. This has been tested in both Azure and GCP with their standard VMs running Ubuntu 20.04.

The nodes have had `linux-headers-$(uname -r)` and `linux-headers-generic` installed.

# Terminal

```shell
Creating symlink /var/lib/dkms/shiftfs/1.2/source ->
                 /usr/src/shiftfs-1.2

DKMS: add completed.

Preparing kernel 5.11.0-1028-azure for module build:
(This is not compiling a kernel, just preparing kernel symbols)
Storing current .config to be restored when complete
Running Generic preparation routine
make mrproper....(bad exit status: 2)
/usr/sbin/dkms: line 1211: .config: Read-only file system
Warning: using /usr/src_node/linux-headers-5.11.0-1028-azure/.config
(I hope this is the correct config for this kernel)
make oldconfig...(bad exit status: 2)
make prepare-all...(bad exit status: 2)

Building module:
cleaning build area...
make -j2 KERNELRELEASE=5.11.0-1028-azure -C /usr/src_node/linux-headers-5.11.0-1028-azure M=/var/lib/dkms/shiftfs/1.2/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.11.0-1028-azure (x86_64)
Consult /var/lib/dkms/shiftfs/1.2/build/make.log for more information.
```

# /var/lib/dkms/shiftfs/1.2/build/make.log

```shell
DKMS make.log for shiftfs-1.2 for kernel 5.11.0-1028-azure (x86_64)
Sun Feb 13 17:10:45 UTC 2022
make: Entering directory '/usr/src_node/linux-headers-5.11.0-1028-azure'
  CC [M]  /var/lib/dkms/shiftfs/1.2/build/shiftfs.o
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c: In function 'shiftfs_fiemap':
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c:727:13: error: dereferencing pointer to incomplete type 'struct fiemap_extent_info'
  if (fieinfo->fi_flags & FIEMAP_FLAG_SYNC)
             ^~
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c:727:26: error: 'FIEMAP_FLAG_SYNC' undeclared (first use in this function); did you mean 'FS_XFLAG_SYNC'?
  if (fieinfo->fi_flags & FIEMAP_FLAG_SYNC)
                          ^~~~~~~~~~~~~~~~
                          FS_XFLAG_SYNC
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c:727:26: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c: In function 'shiftfs_btrfs_ioctl_fd_restore':
/var/lib/dkms/shiftfs/1.2/build/shiftfs.c:1422:2: error: implicit declaration of function '__close_fd'; did you mean 'close_fd'? [-Werror=implicit-function-declaration]
  __close_fd(current->files, fd);
  ^~~~~~~~~~
  close_fd
cc1: some warnings being treated as errors
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/shiftfs/1.2/build/shiftfs.o' failed
make[1]: *** [/var/lib/dkms/shiftfs/1.2/build/shiftfs.o] Error 1
Makefile:1849: recipe for target '/var/lib/dkms/shiftfs/1.2/build' failed
make: *** [/var/lib/dkms/shiftfs/1.2/build] Error 2
make: Leaving directory '/usr/src_node/linux-headers-5.11.0-1028-azure'
```

**Comment by mrsimonemms** [comment]
Closing this as we `fuse` is fixed in [2022.02.0](https://github.com/gitpod-io/gitpod/releases/tag/2022.02.0)

This doesn't solve if you need to use `shiftfs`, but this is now an edge case
